### ISSUE TITLE
Investigate this

### ISSUE THREAD

**Issue by sirugh** [aeosynth/draft#128]
Picking your cards by dragging would be awesome.
https://github.com/jrowny/react-absolute-grid

**Comment by manpages** [comment]
It's a bad UX, in any use case.

Not everyone is playing in stacked mode, so let's consider full-card mode first.

In a full-card mode you'd have to drag all the way down, significantly slowing down the process and requiring to scroll while you drag (error prone from the coding perspective and causes misclicks from UX perspective);

Now consider stacked mode. In stacked mode you sometimes click on things, but hesitate and make it a long click. If you don't have a precision of a StarCraft / Quake player, you might end up dragging the card you don't really want to pick, worst of all, you may first pick Bog Imp vs Flying Men this way. :)

Current two-click approach is the best, however, it's worth noting that it can be further improved by highlighting the card used clicked once (the pre-selected card), and making pre-selected card to get selected if the timer reaches zero, instead of a random card.
